### ISSUE TITLE
Menambahkan Deskripsi Repositori dan Menghapus Kode yg Tidak Perlu

### ISSUE THREAD

**Issue by jefrydco** [KukuhKKH/cari-teks#1]
Hi Mas Kukuh, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Kukuh.

Mas juga sudah menggunakan kerangka kerja Bootstrap untuk membuat aplikasi pencari teks pada video YouTube ini. Luar biasa Mas!

Namun saya ada 2 saran Mas

1. Menambahkan Deskripsi Repositori
Agar repositori kita memiliki deskripsi, Mas bisa menambahkan berkas bernama `readme.md` di dalam direktori proyeknya Mas. Contohnya seperti ini Mas, https://github.com/jefrydco/jefrydco/blob/master/README.md

Hasilnya nanti akan seperti berikut:

![jefrydco](https://user-images.githubusercontent.com/20434351/89712748-0c804280-d9bd-11ea-8623-505f3e98fa15.png)

Pada berkas tersebut Mas juga dapat menuliskan deskripsi seputar aplikasi pada repo ini dan bagaimana cara menjalankannya. Mas dapat menggunakan penulisan [berformat markdown](https://guides.github.com/features/mastering-markdown/) atau HTML.

2. Menghapus Kode yg Tidak Perlu
Pada berkas `index.html` baris ke 67-69 Mas menambahkan perpustakaan JavaScript eksternal jQuery, Bootstrap dan Choices. Menurut saya Mas bisa menghapus ketiga perpustakaan JavaScript eksternal tersebut Mas, karena saya lihat Mas tidak menggunakannya. Bahkan Bootstrap pun Mas hanya menggunakan kerangka kerja CSS nya saja.

Semanagt Mas! 😄

**Comment by KukuhKKH** [comment]
Selamat malam mas Jefry, terima kasih banyak telah mengoreksi hasil proyek
saya serta memberikan sarannya,  untuk kedepannya akan saya tingkatkan lagi
mas, terima kasih mas
